### ISSUE TITLE
403 Error for service accounts trying to add repository

### ISSUE THREAD

**Issue by ashwinphilipgeorge** [appscode/charts#488]
Hi,

Previously, I have been using the appscode/kubed application in my environments, without any issue. I deploy it into my environment using Flux, which polls the appscode helm chart to reconcile any changes. As of a few hours ago, it seems that my Flux application is unable to pull the repository anymore, with the following error code:

```
failed to fetch Helm repository index: failed to cache index to temporary file: failed to fetch https://charts.appscode.com/stable/index.yaml : 403 Forbidden
```

On top of this, it seems like other services, such as Gitlab runners, are also unable to pull the repository as well with a similar error:

```
Error: looks like "https://charts.appscode.com/stable/" is not a valid chart repository or cannot be reached: failed to fetch https://charts.appscode.com/stable/index.yaml : 403 Forbidden
```

The weird part is that we are able to locally pull these helm charts ourselves. However if pulled through a service account, we seem to have authorisation issues.

The command used by these applications is `helm repo add appscode https://charts.appscode.com/stable/ -- force-update`

Trying to access the url https://charts.appscode.com/stable/ also returns an Access Denied error.

**Comment by pinkfloydx33** [comment]
Getting the same from our fluxcd setup; spamming 403 since last night

**Comment by procinger** [comment]
We get since tonight the same 403 error

```
  Error: looks like "https://charts.appscode.com/stable/" is not a valid chart repository or cannot be reached: failed to fetch https://charts.appscode.com/stable/index.yaml : 403 Forbidden
```

**Comment by gavinclarkeuk** [comment]
Getting the same issue from flux. I'm able to request the chart index locally,  but when I request it from inside our clusters I'm getting some kind of JS Challenge back, guessing from Cloudflare or something similar. I'm guessing this is either an over zealous rate limiter, or some kind of bot detection.

**Comment by sambitr** [comment]
Seems there are lot many on the same boat. I am getting the same 403 error through Flux while accessing https://charts.appscode.com/stable

failed to download repository index: failed to cache index to '/tmp/chart-index-14904ode.com/stable/index.yaml : 403 Forbidden

and not able to add the repo manually as well

$  helm repo add appscode https://charts.appscode.com/stable/ -n test
Error: looks like "https://charts.appscode.com/stable/" is not a valid chart repository or cannot be reached: failed to fetch https://charts.appscode.com/stable/index.yaml : 403 Forbidden

**Comment by tamalsaha** [comment]
I am looking into this. I don't see any specific issue in Cloudflare or GCS bucket where we have the data.

https://charts.appscode.com/stable/index.yaml
https://storage.googleapis.com/charts.appscode.com/stable/index.yaml

**Comment by tamalsaha** [comment]
I am looking into this. I don't see any specific issue in Cloudflare or GCS bucket where we have the data.

https://charts.appscode.com/stable/index.yaml

**Comment by gavinclarkeuk** [comment]
If I run `curl https://charts.appscode.com/stable/index.yaml` from inside my cluster I get a cloudflare html page back. I won't put the whole thing here, but the footer is:
```
    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>7a85634cadd5dca7</code></div>
            </div>
            <div class="text-center" id="footer-text">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>
```

**Comment by sambitr** [comment]
I am still getting the same error on the kubernetes cluster through flux and when trying to run locally:

$ helm repo add appscode https://charts.appscode.com/stable/
Error: looks like "https://charts.appscode.com/stable/" is not a valid chart repository or cannot be reached: failed to fetch https://charts.appscode.com/stable/index.yaml : 403 Forbidden

**Comment by tamalsaha** [comment]
I had turned on Cloudflare bot detection thing. I just turned it off again. Does that help?

<img width="1055" alt="Screenshot 2023-03-15 at 7 23 18 AM" src="https://user-images.githubusercontent.com/94814/225338862-3c4513f3-0f1b-405b-b1db-faced860e19b.png">

**Comment by sambitr** [comment]
yes now it helps locally

$ helm repo add appscode https://charts.appscode.com/stable/
"appscode" has been added to your repositories

**Comment by tamalsaha** [comment]
Sorry about the problem. Learned something new today. Reopen if the issue remains.
